name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          build: npm run build
          start: npm run start
      - run: ls -al
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: overgudie.com
          username: site
          key: ${{ secrets.MINOTAUR_SSH_KEY }}
          script: whoami